version: '3.8'

services:

  php-apache-environment:
    image: php:8.0-apache
    container_name: php-apache
    build:
      context: ./serverPHP
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - C:\Users\david\Desktop\Master_Full_Stack\PHP\exam\serverPHP:/var/www/html/
    ports:
      - "8000:80"

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db